language: node_js
node_js:
  - "6"

cache: yarn

env:
  global:
    - CI: true
    - NODE_ENV: "production"

script:
  - yarn build
  - yarn global add firebase-tools
  - cd functions
  - yarn
  - cd ..
  - firebase deploy --token ${FIREBASE_TOKEN}
