language: node_js
node_js:
  - "6"

cache: yarn

env:
  global:
    - CI: true
    - NODE_ENV: "production"

script:
  - yarn build

after_success:
  - yarn global add firebase-tools
  - echo $TEST
  - echo ${TEST}
  - firebase deploy --token ${FIREBASE_TOKEN}
