language: node_js
node_js:
  - "6"

cache: yarn

env:
  global:
    - CI: true
    - NODE_ENV: "production"

branches:
  only:
  - master

before_script:
  - chmod +x travis.sh

script:
  - yarn lint
  - yarn test
  - yarn build
  - ./travis.sh
