language: node_js
node_js:
  - "6"

cache: yarn

env:
  global:
    - CI: true
    - NODE_ENV: "production"

before_script:
  - yarn global add firebase-tools

script:
  - yarn build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

deploy:
  provider: firebase
  token:
    secure: ""
